<?php
/**
 * Author: dungang
 * Date: 2017/3/7
 * Time: 9:31
 */

namespace dungang\payment\weixin;

/**
 * Class Query 查询订单
 * 该接口提供所有微信支付订单的查询，商户可以通过查询订单接口主动查询订单状态，完成下一步的业务逻辑。
 * 需要调用查询接口的情况：
 * https://api.mch.weixin.qq.com/pay/orderquery
 * ◆ 当商户后台、网络、服务器等出现异常，商户系统最终未接收到支付通知；
 * ◆ 调用支付接口后，返回系统错误或未知交易状态情况；
 * ◆ 调用被扫支付API，返回USERPAYING的状态；
 * ◆ 调用关单或撤销接口API之前，需确认支付状态；
 *
 * 不需要证书
 * @package dungang\payment\weixin
 *
 * @property string $transaction_id 微信的订单号，建议优先使用
 * @property string $out_trade_no 商户系统内部的订单号，请确保在同一商户号下唯一。
 */
class Query extends Base
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->method = 'orderquery';
    }
}