<?php
/**
 * Author: dungang
 * Date: 2017/3/7
 * Time: 9:52
 */

namespace dungang\payment\weixin;

/**
 * Class RefundQuery 查询退款
 *
 * 接口链接：https://api.mch.weixin.qq.com/pay/refundquery
 *
 * 提交退款申请后，通过调用该接口查询退款状态。退款有一定延时，用零钱支付的退款20分钟内到账，银行卡支付的退款3个工作日后重新查询退款状态。
 *
 * 不需要。
 *
 * @package dungang\payment\weixin
 *
 * @property string $device_info  	自定义参数，可以为终端设备号(门店号或收银设备ID)，PC网页或公众号内支付可以传"WEB"
 * @property string $transaction_id 微信的订单号，建议优先使用
 * @property string $out_trade_no 商户系统内部的订单号，请确保在同一商户号下唯一。
 * @property string $out_refund_no 商户系统内部的退款单号，商户系统内部唯一，同一退款单号多次请求只退一笔
 * @property string $refund_id 微信生成的退款单号，在申请退款接口有返回
 */
class RefundQuery extends Base
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->method = 'refundquery';
    }
}